const topRecipesTypes = {
    FETCH_TOPRECIPES_START: 'FETCH_TOPRECIPES_START',
    FETCH_TOPRECIPES_SUCCESS: 'FETCH_TOPRECIPES_SUCCESS',
    FETCH_TOPRECIPES_FAILURE: 'FETCH_TOPRECIPES_FAILURE'
};

export default topRecipesTypes;